update
M-skyi/news-search pull request #2
Opened 2021-09-12 18:52 UTC by M-skyi

2021-10-12 15:47 UTC, elcodabra requested changes

2021-10-12 15:47 UTC, elcodabra commented on main.js
> +         itemNews.push(el)
вот тут внутри не хватает функции которая будет полноценный блок добавлять в html вместо добавления в переменные

2021-10-12 15:47 UTC, elcodabra commented on main.js
> +         notFoundNews.classList.add("not-found-news--active");
здесь тоже лучше отдельную функции для рисования пустого блока, по хорошему лучше отделить отрисовку блока от получения данных

2021-10-12 15:47 UTC, elcodabra commented on main.js
> +      function getPublishedAt() {
если хочешь разбить на отдельные функции по отрисовке каждого элемента блока, то лучше сами функции вынести за пределы всех функции и сделать их общими, а на вход функции будут приниматься данные для отрисовки

2021-10-12 15:47 UTC, elcodabra commented on main.js
> +}).then((reposData) => {
для комментов пожелания будут такими же

2021-11-02 15:28 UTC, Ellinsa commented on analitics.css
> +    font-family: Roboto;
Некоторые строчки стилей очень часто повторяются, чтобы соблюдать принцип DRY, может их лучше вынести к родителю, куда-то в более общий отдельный селектор. Посмотри на то где часто повторяется одно и тоже еще, пожалуйста

2021-11-02 15:29 UTC, Ellinsa commented on analitics.css
> +.progress-bar {
Попробуй вместо абсолютного позиционирования гриды или те же флексобоксы

2021-11-02 15:31 UTC, Ellinsa commented on analitics.css
> +.progress-second-item{
Тоже самое замечание, если приглядеться то стили все одинаковые за исключением позиционирования , может придумать какие-то более абстрактные обертки и все сделать на флексах\гридах, и обшие стили вынести в отдельный селектор?

2021-11-02 15:39 UTC, Ellinsa commented on analitics.css
> +        width: 100%;
как вариант можно использовать view units  и свойства min/max-height, min/max-width вместо процентов для резинового дизайна, тогда ширина нужных тебе блоков будет динамически подстраиваться под ширину экрана устройства, поиграться и почитать можно тут:
[](https://css-tricks.com/fun-viewport-units/)
[](https://webflow.com/blog/how-and-why-to-use-vh-and-vw-in-webflow)

2021-11-02 15:43 UTC, Ellinsa commented on analitics.html
> +                            <label class="progress-third-item" for="progress-third-item">25</label>
в целом, label тег кажется тут не совсем уместным, он точно тут нужен?
[дока про тег](http://htmlbook.ru/html/label), но если очень хочется то существует другой способ использования тега, просто к сведению

2021-11-02 15:51 UTC, Ellinsa commented on main.js
> +
Здесь можно создать общую функцию , которая будет выполнять все преобразования принимая динамические параметры и возвращать уже результат в нужную переменную, опять же, можно упростить. Принцип DRY тоже здесь уместен

2021-11-02 15:54 UTC, Ellinsa commented on main.js
> +   let seventhDay = `https://nomoreparties.co/news/v2/everything?q=${topic}&from=${fromDate}&to=${fromDate}&sortBy=publishedAt&pageSize=100&apiKey=${apiKey}`;
полагаю все что связанно с запросами и enpoint  и прочее - лучше вынести в отдельный файл, что-то - в файл конфигурации, не смешивать их с бизнес логикой, если заметные общие паттерны в каждом запросе, можно попробовать упростить код, сделать какую-то более абстрактную функцию

2021-11-02 15:55 UTC, HugaidaS commented on main.js
> +
fetch сам ошибки не ловит, если где-то будет ошибка - всё сломается , опять же есть повторения, можно упростить и alert - ом хотя бы предупреждать юзера о возникшей ошибке - затыкание возможных дыр - важная часть работы

2021-11-02 15:57 UTC, Ellinsa commented on main.js
> +      console.log(error)
вместо консоли попробуй выводить сообщение об ошибке пользователю

2021-11-02 15:58 UTC, Ellinsa commented on style.css
> +  color: #000;
для каких-то базовых цветов можно использовать переменные в css, и потом замена значения переменной будет везде заменять на новый цвет, очень удобно

2021-11-02 16:03 UTC, Ellinsa requested changes
Пробегись по комментариям, думаю ты найдешь для себя много полезного, в целом замечание только по нарушению принципа DRY, можешь почитать о нем [здесь](https://code.tutsplus.com/tutorials/3-key-software-principles-you-must-understand--net-25161) и вот [здесь](https://thevaluable.dev/dry-principle-cost-benefit-example/)

2021-11-05 15:00 UTC, elcodabra reviewed
В целом рекомендация – убрать дублирование однотипных действий в коде и в целом выделить действия в функции, чтоб не было подряд сплошняком кода и тогда уже комменты перед каждой частью не надо будет писать – по названию функции должно быть понятно что она делает

2021-11-05 15:00 UTC, elcodabra commented on analitics.html
> +                    <a class="header__logo-link" href="file:///C:/Users/Dell/Documents/GitHub/Test_Valencia_JS/index.html#">NewsAnalyzer</a>
странный путь...

2021-11-05 15:00 UTC, elcodabra commented on analitice.js
> +let dateItem7 = getNumberDay7 +", " + getWeekDay(getWeekDay7).toLowerCase();
предлагаю весь этот блок запихнуть в функцию и сделать через цикл все однотипные действия

2021-11-05 15:00 UTC, elcodabra commented on analitice.js
> +// get analytics by day 3
аналитику по каждому дню тоже можно выделить в функцию у убрать повторение кода

2021-12-01 18:40 UTC, Ellinsa commented on main.js
> +let reposUrl = `https://api.github.com/repos/M-skyi/Test_Valencia_JS/commits`
Можно вынести ссылку в конфиг а запрос в апи файл

2021-12-01 18:53 UTC, Ellinsa commented on modules/analitice.js
> +
Тут можно вынести логику в отдельную функцию, чтобы не повторяться ,

```
function getItemFromLocalStorage(item){
 let dayData = localStorage.getItem(item);
 return JSON.parse(dayData);
}
//потом использовать 
seventhDayData = getItemFromLocalStorage('seventhDay')

//можно попробовать привести обработку дней к массиву , если это не повердит читаемости
```

2021-12-01 18:55 UTC, Ellinsa commented on modules/getApi.js
> +
api - это интерфейс общения с сервером, все статические глобальные переменные можно вынести в конфиги, переменные среды

2021-12-01 18:58 UTC, Ellinsa commented on style.css
>    background-image: url(img/georgia-de-lotz-bg.png);
картинки можно тоже попробовать внести в переменные, если вдруг нужно будет заменить картинку - то заменить придется всего в одном месте

2021-12-01 19:02 UTC, Ellinsa reviewed
В целом в коде всё хорошо, единственное что нужно самому протестировать работу сайта после запроса, чтобы обрабатывать возможные ошибки и добавить понятные алерты для юзера
![image](https://user-images.githubusercontent.com/48504377/144296969-0056d41d-d081-41ec-b82e-67c48402985b.png)

2021-12-09 19:43 UTC, Ellinsa commented on modules/getApi.js
> +
Вот тут замечание старое,  можно вынести формирование даты в отдельную функцию, так будет почище, но это не критично

2021-12-09 19:44 UTC, Ellinsa commented on style.css
> +    margin: 0 0;
а зачем тут нулевой марджин? что он делает?

2021-12-09 19:45 UTC, Ellinsa commented on style.css
>      border-radius: 15px 15px 15px 15px;
если везде 15 px, то не нужно повторять это 4 раза я думаю

2021-12-09 19:46 UTC, Ellinsa commented on style.css
>      padding: 0 0 0 0;
тоже интересно зачем padding 0 еще и 4 раза подряд повторяется, для чего? может можно упростить?

2021-12-09 19:48 UTC, Ellinsa reviewed
В целом всё хорошо, будем ждать ревью Александра

2021-12-16 21:20 UTC, elcodabra requested changes
много повторяющихся действий, пересмотри плиз, может получится намного лаконичнее и безопаснее код

2021-12-16 21:20 UTC, elcodabra commented on modules/analitice.js
> +
со 155 по 171 очень много повторяющихся действий, попробуй упаковать

2021-12-16 21:20 UTC, elcodabra commented on modules/analitice.js
> +
попробуй здесь тоже упаковать в функцию, вместо имен классов count-progress-seventh-item и progress-seventh-item можно например использовать count-progress-item-7 и progress-item-7

2021-12-16 21:20 UTC, elcodabra commented on analitics.html
> +                        <li class="analitics-days__date-item font_family" id="day-1"></li>
можно вынести кстати в js часть и добавлять оттуда в родительский компонент

2021-12-16 21:20 UTC, elcodabra commented on modules/getApi.js
> +   let dayArr = ['firstDay','secondDay','thirdDay','fourthDay','fifthDay','sixthDay','seventhDay'];
очень много потворяющегося

2021-12-27 09:11 UTC, elcodabra requested changes

2021-12-27 09:11 UTC, elcodabra commented on analitics.html
> +                            <div class="progress-item-7 progress-item"></div>
добавлять все блоки через js

2021-12-27 09:11 UTC, elcodabra commented on modules/analitice.js
> +   seventhDayData = getItemFromLocalStorage('seventhDay');
пересмотри хранение в сторадже, сохрани прям весь массив, и по индексу будешь доставать нужное значение, вместо 7 строчек под каждую переменную просто используй массив

2021-12-27 09:11 UTC, elcodabra commented on modules/analitice.js
> + let progressBarItem7 = getProgressItem("count-progress-item-7");
здесь тоже цикл вместо 7 строчек

2021-12-27 09:11 UTC, elcodabra commented on modules/analitice.js
> + let countDayItem7 = getCountDayItem(".progress-item-7");
и здесь, а лучше вынести внутрь функции getCountDayItem

2021-12-27 09:11 UTC, elcodabra commented on modules/analitice.js
> +   getAnalyticsData(firstDayData,progressBarItem1,countDayItem1);
тоже сделать циклом

2021-12-27 09:11 UTC, elcodabra commented on modules/analitice.js
> +let analiticeDayItem7 = getAnaliticeDay("day-7");
и здесь циклом

2021-12-27 09:11 UTC, elcodabra commented on modules/analitice.js
> +correctDate(analiticeDayItem7,0);
и здесь циклом

2021-12-27 09:11 UTC, elcodabra commented on modules/getApi.js
> +const todaysDate = getDate(0 * 24 * 60 * 60 * 1000);
цикл

2021-12-27 09:11 UTC, elcodabra commented on modules/getApi.js
> +   let seventhDay = urlDayNews(fromDate);
массив + цикл

2021-12-27 09:11 UTC, elcodabra commented on modules/getApi.js
> +            if (dayItem === firstDay) {
пересмотреть тут, потому что будешь сохранять сразу массив в сторадж

2021-12-27 09:11 UTC, elcodabra commented on modules/getApi.js
> +       savedlocalStorage(firstDay)
тут тоже пересмотреть

2022-01-16 16:11 UTC, elcodabra requested changes
постараться еще больше потренироваться в выделении в отдельные функции и более эффективного, гибкого и удобного использования: по хорошему не использовать внешние переменные в функциях; много повторений по циклам – пусть будет в одном цикле; стараться разбить код более "модульно", работа с DOM и отрисовка желательно отдельно, логика и данные отдельно.

2022-01-16 16:11 UTC, elcodabra commented on modules/analitice.js
> +      progList.prepend(progLine);
в идеале эту часть вынести в функцию как создание отдельного элемента, а в цикле уже вызывать эту функцию с нужными параметрами, но это больше вкусовщина, скорее более важен такой подход для будущего в реакте

2022-01-16 16:11 UTC, elcodabra commented on modules/analitice.js
> +      arrCountDay.push(countDayItem)
можно было не создавать отдельный цикл, у тебя уже есть такой же на 121 строчке, вынести туда это тело

2022-01-16 16:11 UTC, elcodabra commented on modules/analitice.js
> +      pos = arrDataText.toLowerCase().indexOf(`${topicValueLocal}`.toLowerCase());
по хорошему не использовать внешние переменные в функциях

2022-01-16 16:11 UTC, elcodabra commented on modules/analitice.js
> +   for (let i = 0; i < 7; i++) {
тут тоже подряд 4 цикла, когда можно было эффективнее в одном цикле все сделать, а чтоб выглядело внутри не все как в куче – выделять в отдельные функции

2023-01-01 07:37 UTC, closed without merging