create react app
M-skyi/news-search pull request #3
Opened 2022-01-25 18:03 UTC by M-skyi

2022-02-12 19:48 UTC, Ellinsa commented on react-valencia/src/about_author_modules/AboutAuthor.css
> +.bout-author-text__headline{
у тебя тут кажется опечатка, и что есть bout-author-text__text? может придумать более описательные имена классов?

2022-02-12 19:51 UTC, Ellinsa commented on react-valencia/src/analytics_main_modules/Analytics.css
> +@media(min-width: 320px){
все медиа правила лучше поместить в самый низ css файла

2022-02-12 19:53 UTC, Ellinsa commented on react-valencia/src/analytics_main_modules/AnalyticsMain.jsx
> +
Analytics и AnalyticsMain - синонимы по сути, нужно придумать имена , которые бы давали понять ЧТО конкретно содержит в себе компонент

2022-02-12 19:55 UTC, Ellinsa commented on react-valencia/src/analytics_main_modules/AnalyticsMain.jsx
> +            <ul className="progress-bar">
можно выделить в отдельный компонент ul и каждый li  тоже, и потом рендерить динамически из массива. В целом в этом файле есть еще что разбить на компоненты

2022-02-12 19:56 UTC, Ellinsa commented on react-valencia/src/analytics_main_modules/AnalyticsTop.jsx
> +const AnalyticsTop = (props) => {
AnalyticsTop тоже немного не отражает суть, может лучше уж AnalyticsHeader например?

2022-02-12 19:58 UTC, Ellinsa commented on react-valencia/src/analytics_main_modules/Analytics.jsx
> +      <FooterMain/>
Вот что интересно, почему footer сайта у тебя в компоненте аналитики , хотя по логике он должен быть в App.js под маршрутами? Он же напрямую потомок всего приложения

2022-02-12 20:00 UTC, HugaidaS commented on react-valencia/src/App.js
> +    <div className={"App"}>
я бы предложила структуру следующую:
основная навигация и подвал у сайта всегда едины и напрямую потомки всего приложения, в этом есть смысл
```
<div className={"App"}>
   <NavBar/>
   <Routes/>
   <Footer/>
</div>
```

2022-02-12 20:01 UTC, HugaidaS commented on react-valencia/src/footer_modules/Footer.css
> +@media (min-width: 768px) {
по медиа запросам тот же совет, поместить лучше вниз

2022-02-12 20:05 UTC, HugaidaS commented on react-valencia/src/footer_modules/FooterNav.jsx
> +
можно сделать массив в котором будут объекты ссылок с полями - путь, заголовок; и динамически пройтись по массиву и для каждого итема возвращать компонент ссылки куда вставлять название ссылки и ее путь, таким образом можно избавиться от лишних повторений в коде

2022-02-12 20:07 UTC, HugaidaS commented on react-valencia/src/header_modules/Header.jsx
> +import HeaderMain from "./HeaderMain";
надо был придумать им более описательные имена, HeaderMain и HeaderTop по сути одно и тоже, читая код не понятно чем они отличаются, для компонентов-оберток можно делать приписку Container например

2022-02-12 20:11 UTC, Ellinsa commented on react-valencia/src/header_modules/HeaderTop.jsx
> +
а вот тут как-то совсем уж некрасиво получается, в названии компонента его позиционка? Это только усложнит тебе жизнь, если придется переделывать код может дойти до абсурда, если что-то можно решить css - лучше решить css , но имя компонента должно отражать его содержимое, а не его позицию . Думаю этот компонент особенно нуждается в рефакторинге. Стоит подумать как сделать так, чтобы компоненты можно было использовать потом где угодно в приложении, без привязки к контексту, максимальная реюзабельность по возможности

2022-02-12 20:17 UTC, HugaidaS commented on react-valencia/src/header_modules/HeaderTopLeft.jsx
> +    return(
я думаю это уже слишком маленький компонент) можно поместить это в компонент по крупнее и рендерить ссылки динамически из массива с объектами ссылок ( см. комментарии выше). добавлю еще что при таком подходе достаточно будет изменить массив в верху компонента, а не лезть в код и копаться в поисках ссылки

2022-02-12 20:18 UTC, Ellinsa commented on react-valencia/src/header_modules/HeaderTopRight.jsx
> +
то же самое, надо бы слить это в один компонент, попробуй, так будет почище

2022-02-12 20:34 UTC, Ellinsa commented on react-valencia/src/history_commits_modules/HistoryCommits.css
> +    background-image: url(../project_img/arrowLink.png);
ссылки лучше вынести наверх в переменные

2022-02-12 20:38 UTC, Ellinsa commented on react-valencia/src/history_commits_modules/HistoryCommitsSlider.jsx
> +
сам слайдер перенасыщен слегка, заметно что его можно подразбить на компоненты

2022-02-12 20:40 UTC, Ellinsa commented on react-valencia/src/history_commits_modules/HistoryCommitsTop.jsx
> +const HistoryCommitsTop = () =>{
HistoryCommitsTop - не совсем подходящее название, может CommitsHistoryHeader?

2022-02-12 20:42 UTC, Ellinsa commented on react-valencia/src/index.css
> +
`*box-sizing:border-box;//попробуй указать применение этого свойства для всех элементов по умолчанию, это сильно поможет, может погуглить подробнее свойство`

2022-02-12 20:45 UTC, Ellinsa commented on react-valencia/src/news_main_modules/NewsMain.jsx
> +        <Header/>
опять же - шапка и футер снова используются , хотя они по идее здесь быть не должны, это не совсем логично, шапка и подвал у нас едины для всех страниц насколько я понимаю

2022-02-12 20:49 UTC, Ellinsa commented on react-valencia/src/search_res_modules/SearchResBtn.jsx
> +
если эта кнопка не используется где-то еще и не подразумевается что она будет использоваться где-то еще, думаю можно не выделять ее в отдельный компонент, либо тогда передавать ей пропсы обработчика клика и заголовок  и сделать компонент более абстрактным

2022-02-12 20:53 UTC, Ellinsa commented on react-valencia/src/search_res_modules/SearchResContent.jsx
> +            <SearchResItem/>
не гуд, повторение кода - не гуд. Грубое нарушение чистоты. Антисанитария!))) Если нужно определенное количество элементов - циклы тебе в помощь.

2022-02-12 20:57 UTC, Ellinsa commented on react-valencia/src/search_res_modules/SearchResTop.jsx
> +const SearchResTop = () =>{
SearchResTop > SearchResultHeader пусть имя будет чуть длиннее , но понятнее, чтобы другие потом понимали что это

2022-02-12 21:07 UTC, HugaidaS reviewed
В основном мои советы только по именам компонентов,  также советую оптимизировать крупные картинки в формат webp  и прогнать потом приложение на speedtest  в гугле

2022-06-03 21:28 UTC, elcodabra requested changes

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/App.js
> +    if (location.pathname === "/analytics") {
это условие лучше вынести в useEffect

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/App.js
> +      setSearchResult(false)
много функций которые делают только одно действие, не очень эффективно, в дальнейшем для функций можно использовать еще useCallback, чтоб функция не объявлялась каждый раз по новой, почитай про это

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/api/api.js
> +       let getDate = new Date(new Date().getTime() - (i * 24 * 60 * 60 * 1000)).toLocaleDateString('sv-SE');
sv-SE зачем? лучше совсем убрать параметр

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/api/api.js
> +    export let getInputValue = (newsTopic) => {
export const getInputValue

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/api/api.js
> +export {
можно по аналогии с getInputValue

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/app/main.js
> +    changeDate
и тут по аналогии с getInputValue

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/analytics_main/Analytics.jsx
> +  let topicRequest = JSON.parse(localStorage.getItem("topic"));
такие штуки можно выносить за пределы компонента, тут нет нкаких зависимостей от компонета

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/analytics_main/Analytics.jsx
> +  let topicRequest = JSON.parse(localStorage.getItem("topic"));
если только хранилще не будет меняться

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/analytics_main/Analytics.jsx
> +      function getDataLocalStor() {
функции лучше выносить как независимые

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/analytics_main/AnalyticsHeader.jsx
> +    }
наверное можно оформить в независмую функцию, потому что используешь только 3 переменые для компонента

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/analytics_main/AnalyticsProgressBar.jsx
> +        dates.reverse()
тоже лучше в отдельную фунцию

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/analytics_main/AnalyticsProgressBar.jsx
> +               date={dates[index]}
item лучше вместо dates[index]

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/analytics_main/AnalyticsProgressBarItem.jsx
> +const AnalyticsProgressBarItem = (props) =>{
обычно делают так ({ count }) => {

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/header/Header.jsx
> +    function headerAnalytic() {
лучше сделать независимой функцией

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/header/Header.jsx
> +        <div className={`${classHeader.headerMain} ${classHeader.headerAnalytic}`}>
можно использовать библиотеку для работы с классами classnames, упрощает

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/header/Header.jsx
> +                 showNoNewsFound = {props.showNoNewsFound}
про парметры в props писал выше

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/header/HeaderNavLeft.jsx
> +    if (location.pathname === "/analytics") {
useEffect + classnames

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/history_commits/HistoryCommitsMain.jsx
> +       <div className={"history-commits-main"}>
можно просто className="history-commits-main"

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/history_commits/HistoryCommitsSlider.jsx
> +          backgroundSize:"cover"
лучше вынести в класс

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/history_commits/HistoryCommitsSlider.jsx
> +    let settings = {
можно вынести за пределы компонента

2022-06-03 21:28 UTC, elcodabra commented on react-valencia/src/components/search_result/SearchResultContent.jsx
> +             url = {dataObjNews.arrUrl[index]}
возможно лучше через item сделать

2022-07-08 19:08 UTC, elcodabra requested changes
это вкусовщина, но советую код такого вида оформлять так - (нормально не вставляется оформление кода, если что у меня спроси)
`
{headerContent &&  (
            <HeaderContent
              showLoader={showLoader}
              hideLoader={hideLoader}
              showNoNewsFound={showNoNewsFound}
              hideNoNewsFound={hideNoNewsFound}
              showSearchResult={showSearchResult}
              hideSearchResult={hideSearchResult}
              loaderChange={loader}
            />
          )
`

2022-07-08 19:08 UTC, elcodabra commented on react-valencia/src/components/analytics_main/AnalyticsProgressBar.jsx
> +    item.reverse()
лучше сразу цикл for обратный делать, неэффективно в два цикла, reverse внутри по сути второй цикл делает

2022-07-08 19:08 UTC, elcodabra commented on react-valencia/src/components/analytics_main/AnalyticsProgressBarItem.jsx
> +        <div className={"analytics-progress-bar-item"}>
структура должна быть ul -> li, у тебя тут получается ul -> div -> li, надо переделать

2022-07-08 19:08 UTC, elcodabra commented on react-valencia/src/components/footer/FooterNav.jsx
> +               <Link className={"footer-nav__item"} to="/">Главная</Link>
одни ссылки через Link, другие через тег a, лучше одно что то выбрать

2022-07-08 19:08 UTC, elcodabra commented on react-valencia/src/components/header/Header.jsx
> +    const headerClass = classNames({
если есть зависимости от параметров компонента или других переменных лучше делать через useMemo, чтоб не было лишних перерисовок, посмотри в других частях кода тоже, чтоб сделать более эффективный рендер компонентов

2022-07-15 17:16 UTC, M-skyi commented on react-valencia/src/api/api.js
> +       let getDate = new Date(new Date().getTime() - (i * 24 * 60 * 60 * 1000)).toLocaleDateString('sv-SE');
Параметр мне дает правильный формат даты 2022-07-15
такой же как в документации на сайте NewsAPI

https://newsapi.org/v2/everything?q=tesla&from=2022-06-15&sortBy=publishedAt&apiKey=1bb2c66fe49f4cc8aae2c07724edd0bd

Если без этого параметра получаю формат  2022.07.15
и запрос не срабатывает ((

2022-07-16 18:07 UTC, M-skyi commented on react-valencia/src/components/history_commits/HistoryCommitsSlider.jsx
> +          backgroundSize:"cover"
Тут не могу нигде найти как выносить эти настройки в class , если есть какая то статья или сам подскажи как )
а то не могу на гуглить как это сделать . Пока что вынес эти настройки в отдельный файл

2022-07-17 13:40 UTC, M-skyi commented on react-valencia/src/components/search_result/SearchResultContent.jsx
> +             url = {dataObjNews.arrUrl[index]}
тут через item не получается  сделать .  itemResult это массив из 3 компонентов <SearchResultItem /> что бы новости выводились по 3 элемента  и потом к ним уже добавляю данные из массива .
Если делать  arrayData.map() то вываливает сразу все новости ((
Пока что не выходит сделать через Item если сильно критично подскажи пожалуйста как правильно сделать )

2023-01-01 07:38 UTC, closed without merging